### ISSUE TITLE
Just a precision

### ISSUE THREAD

**Issue by benckx** [lucaferranti/awesome-xiangqi#1]
The Analysis Board on https://elephantchess.io doesn't support Fairy Stockfish - we use only Pikafish by default for all analysis. But you can select that engine to play against. Also we have a database of games.

Thanks for the mention :)

**Comment by agogugu** [comment]
Ciao Luca. Per la parte di storia e per la parte introduttiva agli xiangqi c'è anche 
https://www.amazon.it/dp/B0CNLTKS34
XIANGQI Introduction to Chinese Chess for beginners: The basics Tactics and Strategy Openings Middlegame Endgame History di mia moglie Lin Ye ;-)

**Comment by lucaferranti** [comment]
@agogugu grazie!

Conosco il libro e, se non sbaglio, è già incluso nella lista nella sezione https://github.com/lucaferranti/awesome-xiangqi?tab=readme-ov-file#introductory-books ?


@benckx thanks for the correction, I am updating some fixes today and will clarify that section

**Comment by agogugu** [comment]
Grazie mille Luca,
   mi era sfuggito.

Grazie ancora e buona giornata :-)

**Comment by lucaferranti** [comment]
elephantchess.io inaccuracies fixed in c0bd51c . The websites to play section is now a table, which should make comparison easier, do let me know if I still got something wrong :)

**Comment by agogugu** [comment]
Ciao Luca,
   per tua informazione
https://youtu.be/YcjFsELBByI
***@***.***?si=bGqMZDWfpvopG4rV

Buona giornata

**Comment by agogugu** [comment]
Ciao Luca,
per tua conoscenza :-)

https://italianxiangqi.wordpress.com/
https://italianxiangqi.wordpress.com/posts/
https://italianxiangqi.wordpress.com/about/

Agostino
